import "@repo/ui/styles/global.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import localFont from "next/font/local"
import { cn } from "@repo/ui"

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo"
}

// Define the font styles
const fontSans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: "400"
})

const fontHeading = localFont({
  src: "../assets/fonts/CalSans-SemiBold.woff2",
  variable: "--font-heading"
})

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen scroll-smooth bg-background font-heading antialiased",
          fontSans.variable,
          fontHeading.variable
        )}
      >
        {children}
      </body>
    </html>
  )
}
