import { RouteEnums } from "../router/route-constants";

export const PERMISSIONS = {
  STAFF: {
    CREATE: "STAFF_CREATE",
    READ: "STAFF_READ",
    UPDATE: "STAFF_UPDATE",
    DELETE: "STAFF_DELETE",
  },
  STUDENT: {
    CREATE: "STUDENT_CREATE",
    READ: "STUDENT_READ",
    UPDATE: "STUDENT_UPDATE",
    DELETE: "STUDENT_DELETE",
  },
  CLASS: {
    CREATE: "CLASS_CREATE",
    READ: "CLASS_READ",
    UPDATE: "CLASS_UPDATE",
    DELETE: "CLASS_DELETE",
  },
  SUBJECT: {
    CREATE: "SUBJECT_CREATE",
    READ: "SUBJECT_READ",
    UPDATE: "SUBJECT_UPDATE",
    DELETE: "SUBJECT_DELETE",
  },
  TIMETABLE: {
    CREATE: "TIMETABLE_CREATE",
    READ: "TIMETABLE_READ",
    UPDATE: "TIMETABLE_UPDATE",
    DELETE: "TIMETABLE_DELETE",
  },
  PERIOD: {
    CREATE: "PERIOD_CREATE",
    READ: "PERIOD_READ",
    UPDATE: "PERIOD_UPDATE",
    DELETE: "PERIOD_DELETE",
  },
} as const;

export const routePermissionsMap = {
  // Test
  [RouteEnums.LOGS]: ["PERMISSIONS.LOGS"],
};
