import { RouteEnums } from "../router/route-constants";

export const PERMISSIONS = {
  STAFF: {
    CREATE: "STAFF_CREATE",
    READ: "STAFF_READ",
    UPDATE: "STAFF_UPDATE",
    DELETE: "STAFF_DELETE",
  },
  STUDENT: {
    CREATE: "STUDENT_CREATE",
    READ: "STUDENT_READ",
    UPDATE: "STUDENT_UPDATE",
    DELETE: "STUDENT_DELETE",
  },
  STUDENT_GRADE: {
    CREATE: "STUDENT_GRADE_CREATE",
    READ: "STUDENT_GRADE_READ",
    UPDATE: "STUDENT_GRADE_UPDATE",
    DELETE: "STUDENT_GRADE_DELETE",
  },
  STUDENT_SUBJECT_REGISTRATION: {
    CREATE: "STUDENT_SUBJECT_REGISTRATION_CREATE",
    READ: "STUDENT_SUBJECT_REGISTRATION_READ",
    UPDATE: "STUDENT_SUBJECT_REGISTRATION_UPDATE",
    DELETE: "STUDENT_SUBJECT_REGISTRATION_DELETE",
  },
  CLASS: {
    CREATE: "CLASS_CREATE",
    READ: "CLASS_READ",
    UPDATE: "CLASS_UPDATE",
    DELETE: "CLASS_DELETE",
  },
  CLASS_DIVISION: {
    CREATE: "CLASS_DIVISION_CREATE",
    READ: "CLASS_DIVISION_READ",
    UPDATE: "CLASS_DIVISION_UPDATE",
    DELETE: "CLASS_DIVISION_DELETE",
  },
  CLASS_PROMOTION: {
    CREATE: "CLASS_PROMOTION_CREATE",
    READ: "CLASS_PROMOTION_READ",
    UPDATE: "CLASS_PROMOTION_UPDATE",
    DELETE: "CLASS_PROMOTION_DELETE",
  },
  SUBJECT: {
    CREATE: "SUBJECT_CREATE",
    READ: "SUBJECT_READ",
    UPDATE: "SUBJECT_UPDATE",
    DELETE: "SUBJECT_DELETE",
  },
  SUBJECT_GRADE: {
    CREATE: "SUBJECT_GRADE_CREATE",
    READ: "SUBJECT_GRADE_READ",
    UPDATE: "SUBJECT_GRADE_UPDATE",
    DELETE: "SUBJECT_GRADE_DELETE",
  },
  SUBJECT_GRADE_BREAKDOWN: {
    CREATE: "SUBJECT_GRADE_BREAKDOWN_CREATE",
    READ: "SUBJECT_GRADE_BREAKDOWN_READ",
    UPDATE: "SUBJECT_GRADE_BREAKDOWN_UPDATE",
    DELETE: "SUBJECT_GRADE_BREAKDOWN_DELETE",
  },
  TIMETABLE: {
    CREATE: "TIMETABLE_CREATE",
    READ: "TIMETABLE_READ",
    UPDATE: "TIMETABLE_UPDATE",
    DELETE: "TIMETABLE_DELETE",
  },
  SCHOOL_GRADING_POLICY: {
    CREATE: "SCHOOL_GRADING_POLICY_CREATE",
    READ: "SCHOOL_GRADING_POLICY_READ",
    UPDATE: "SCHOOL_GRADING_POLICY_UPDATE",
    DELETE: "SCHOOL_GRADING_POLICY_DELETE",
  },
  PERIOD: {
    CREATE: "PERIOD_CREATE",
    READ: "PERIOD_READ",
    UPDATE: "PERIOD_UPDATE",
    DELETE: "PERIOD_DELETE",
  },
  SCHOOL: {
    CREATE: "SCHOOL_CREATE",
    READ: "SCHOOL_READ",
    UPDATE: "SCHOOL_UPDATE",
    DELETE: "SCHOOL_DELETE",
  },
  SCHOOL_CALENDAR: {
    CREATE: "SCHOOL_CALENDAR_CREATE",
    READ: "SCHOOL_CALENDAR_READ",
    UPDATE: "SCHOOL_CALENDAR_UPDATE",
    DELETE: "SCHOOL_CALENDAR_DELETE",
  },
  SCHOOL_TIMETABLE: {
    CREATE: "SCHOOL_TIMETABLE_CREATE",
    READ: "SCHOOL_TIMETABLE_READ",
    UPDATE: "SCHOOL_TIMETABLE_UPDATE",
    DELETE: "SCHOOL_TIMETABLE_DELETE",
  },
  ROLE: {
    CREATE: "ROLE_CREATE",
    READ: "ROLE_READ",
    UPDATE: "ROLE_UPDATE",
    DELETE: "ROLE_DELETE",
  },
} as const;

export const routePermissionsMap = {
  // Test
  [RouteEnums.LOGS]: ["PERMISSIONS.LOGS"],
};
